### ISSUE TITLE
error in addon:"/io_obj_as_shapekey.py"

### ISSUE THREAD

**Issue by ge53** [meta-androcto/blenderpython#10]
Traceback (most recent call last):
  File "/Users/geraldine/Library/Application Support/Blender/2.77/scripts/addons/io_obj_as_shapekey.py", line 59, in execute
    sknames = [sk.name for sk in target.data.shape_keys]
TypeError: 'NoneType' object is not iterable

location: <unknown location>:-1

(i am on Mac elCapitan)--any help much appreciated!

**Comment by meta-androcto** [comment]
hi, I'll have to test it out, I loosely maintain my addons collection, if I can fix easily i will fix, if not i'll remove from my collection.
do you have a link at all to the original file? (not from my repo)

**Comment by ge53** [comment]
this has been solved--thank you
"_Well, the first thing to notice is that

target.data.shape_keys.key_blocks
is a null or empty object at the point of the error and thus the script cannot execute the for loop to fill the sknames object.

Upon looking into this further it seems the issue is with the file path that references the location of the obj files around line 56 (at least it did for me).

Replacing this:

for f in files:
    fp = spath[0] + "\\" + f
with this:

for f in files:
    fp = os.path.join(spath[0], f)
seemed to solve it for me._"

from Todd McIntosh, Blender Stackexchange
Thanks.
