### ISSUE TITLE
AF: Materials Specials

### ISSUE THREAD

**Issue by tiagocardoso** [meta-androcto/blenderpython#13]
Hello,

I'm using your AF: Materials Specials mashup on a project.
I've notice that the code have disappeared from you git hub directory. Was this just a move or you did delete it ? We need to automatically convert blender render materials to cycles renderer.

Is it strictly oss ? Can we distribute it with blender on a docker hub image ?
Thank you in advance.

**Comment by meta-androcto** [comment]
hi! Materials Specials & conversion in in Blender 2.78!
It will be released soon, also has been in blender buildbot builds for some time.
We have done significant work on this & it's much improved.

**Comment by tiagocardoso** [comment]
Hi.
We are already using 2.78 and the new addon. Yes, it is improved!! :D

Thank you for the work ;)
